- app/Game.php
- app/Http/Controllers/GameController.php
- app/Http/Controllers/UserController.php
- app/Inventory.php
- app/Providers/AppServiceProvider.php
- database/factories/UserFactory.php
- database/migrations/2018_02_02_020613_create_users_table.php
- database/migrations/2018_02_02_020703_create_games_table.php
- database/migrations/2018_02_02_020736_create_inventories_table.php
- database/migrations/2018_02_02_020856_create_friends_table.php
- database/migrations/2018_02_02_025538_create_password_resets_table.php
- database/seeds/GamesTableSeeder.php
- database/seeds/UsersTableSeeder.php
The comment above states what we did during class, if anyone needs further explanation please ask :)
> create controllers, models, factories, dummmy data round one

- databasespecs.md
- tests/Feature/FontEndWelcomeTest.php
- tests/Feature/SchemaTest.php
This branch had some hidden test on it from class on Thursday but it's mostly the review of the Database specs.
> Kc n8dbspec

- public/css/app.css
- resources/assets/sass/app.scss
- resources/views/browse.blade.php
- resources/views/layouts/main.blade.php
- routes/web.php
This PR address #49. Build the route and base page for the browse view.
> added new route for browse

- app/Http/Controllers/Auth/RegisterController.php
- app/User.php
- resources/views/auth/register.blade.php
Added username data field and setup authentication in our main template.
> added authentication to new pages

- app/Http/Controllers/Auth/LoginController.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/main.blade.php
- routes/web.php
Added logout option on main template.
> added option to logout

- app/Http/Controllers/Auth/LoginController.php
- resources/views/home.blade.php
- resources/views/partials/navbar.blade.php
- routes/web.php
added navbar login and logout.
> added log in and log out to the navbar

- public/js/bootstrap.js
- public/js/jquery-3.3.1.js
- public/js/jquery.flip.js
- public/mix-manifest.json
- resources/assets/js/jquery-3.3.1.js
- resources/assets/js/jquery.flip.js
- resources/views/layouts/main.blade.php
- webpack.mix.js
> Added jQuery and jQuery Flip.

- public/css/app.css
- public/css/featherlight.css
- public/js/featherlight.js
- public/js/jquery-3.3.1.js
- public/js/jquery.flip.js
- public/mix-manifest.json
- resources/assets/js/featherlight.js
- resources/assets/sass/app.scss
- resources/views/layouts/main.blade.php
- resources/views/partials/game.blade.php
- resources/views/partials/games.blade.php
- webpack.mix.js
> added featherlight and created game component

- composer.json
- composer.lock
We will need everyone to change .env file APP_URL to include :8888
then run
$composer update
$php artisan dusk:install
> We are hooked up to Dusk which will be our Browser testing suite :)

- resources/assets/sass/app.scss
- resources/views/partials/friends.blade.php
- resources/views/partials/profile.blade.php
> added friends component; aligned the friends' notification dropdown

- routes/web.php
> Fixes #131 uncomment Auth::routes()

- app/Providers/ComposerServiceProvider.php
> defining a variable

- public/mix-manifest.json
removing more autogenerated files that art conflicting with git
> removed mix-manifest

- composer.lock
> ran composer update

- public/css/featherlight.css
- resources/assets/sass/app.scss
- resources/views/auth/login.blade.php
- resources/views/landing.blade.php
- resources/views/layouts/landing.blade.php
this is all the UI/UX stuff i have worked on! including (opposite order): settings page, browse results, the filter, pagination, login page, having the landing page connect to the login page. please pull my request. THANKS
> Cjt new branch

- app/Game.php
- resources/views/partials/item-owner.blade.php
- resources/views/partials/profile.blade.php
resolve issues with games not showing up as owned. Made it so the remove friend button down not show in the auth user profile page.
> resolved owned game issue and add friend on auth users profile

- database/seeds/MasterTableSeeder.php
two users in DB.  Winnie and Peggy.  They are friends with eachother, own games, and are borrowing games from eachother.
> two dummies flushed out

- database/seeds/MasterTableSeeder.php
- tests/Unit/DatabaseTest.php
Updated test query to get a populated inventory. Tested all data types.
Updated seeder to include date and return date on borrowed inventories.
> updated query to get a populated inventory and resolved tests

- resources/views/partials/filter.blade.php
- resources/views/partials/item.blade.php
- resources/views/partials/navbar.blade.php
- resources/views/settings.blade.php
still have a few to do but kelsey needs access to the ones ive done
> adding dusk tags

- resources/views/partials/item-full.blade.php
- resources/views/partials/item-owner.blade.php
- resources/views/partials/item.blade.php
- resources/views/partials/profile.blade.php
- resources/views/settings.blade.php
> dusk tags done

- database/seeds/MasterTableSeeder.php
> fixed winnies name

- database/seeds/MasterTableSeeder.php
updated the first 4 games in browse.  as well as monopoly, life, clue, bang, catan, pandemic, battleship, bop-it, and payday
> game data updated
